name: test_app_3d
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_map:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  geolocator: ^7.2.0
  google_maps_flutter: ^2.0.2
  font_awesome_flutter: ^9.1.0
  flutter_polyline_points: ^1.0.0
  geocoding: ^2.0.0
  syncfusion_flutter_maps: ^19.2.46-beta
  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0
  fluttertoast: ^8.0.7
  google_sign_in: ^5.0.4
  provider: ^5.0.0
  flutter_signin_button: ^2.0.0
  http: ^0.13.3
  flutter_rating_bar: ^4.0.0
  url_launcher: ^6.0.9
  location: ^4.3.0
  flutter_html: ^2.1.0
  webview_flutter: ^2.0.9
  flutter_webview_plugin: ^0.4.0
  shared_preferences: ^2.0.6
  like_button: ^2.0.2
  flutter_compass: ^0.6.1
  syncfusion_flutter_charts: ^19.2.46+1
  google_fonts: ^2.1.0
  flutter_launcher_icons: ^0.9.0







dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  android: true
  ios: true
  image_path: "images/nen.jpg"


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true



  # To add assets to your application, add an assets section, like this:
  assets:
    - images/aa.png
    - images/harita.png
    - images/tr-cities.json
    - images/bb.png
    - images/ba.png
    - images/r.png
    - images/eee.png
    - images/city.png
    - images/3d.png
    - images/eye.png
    - images/australia.json
    - images/map2.html
    - images/login.png
    - images/voronoi.png
    - images/fl.png
    - images/navanie.png
    - images/dee.png
    - images/quot.png
    - images/nevk.png
    - images/matya.png
    - images/olk.png
    - images/design.png
    - images/desk.png
    - images/arc.png
    - images/greyy.png
    - images/vilde.png
    - images/vild.png
    - images/vera.png
    - images/world_map.json
    - images/donatt.png
    - images/chart.png
    - images/bbee.png
    - images/tink.png
    - images/pinko.png
    - images/gooe.png
    - images/tell.png
    - images/ara.png
    - images/pusula.png
    - images/held.png



  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
